name: CI/CD Prod

on:
  push:
    branches: [ postgres ]
  workflow_dispatch: {}

jobs:

  build_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      env:
        GH_USER: gsmcwhirter
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: echo "$GH_TOKEN" | docker login ghcr.io -u "$GH_USER" --password-stdin

    - name: Build the bot image  
      run: ./bin/botctl docker build bot:$GITHUB_SHA bot

    - name: Push the bot image w/ sha
      run: ./bin/botctl docker push signup-bot:$GITHUB_SHA-bot

    - name: Re-tag the bot image prod
      run: docker tag signup-bot:$GITHUB_SHA-bot signup-bot:prod-bot

    - name: Push the prod bot image
      run: ./bin/botctl docker push signup-bot:prod-bot

    - name: Deploy the docker image
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/ && \
        echo "$SSH_PRIVATE_KEY" > ../github_do.key && \
        sudo chmod 600 ../github_do.key && \
        ssh-keyscan -H "$DEPLOY_SERVER" > ~/.ssh/known_hosts && \
        ssh -i ../github_do.key cicd@"$DEPLOY_SERVER" 'sudo /bin/systemctl restart signup-bot.service'